version: '3.8'

networks:
  mynetwork:

services:

  php:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www
    depends_on:
      - mysql
    networks:
      - mynetwork

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: symfony
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - mynetwork

  symfony:
    build:
      context: .
    depends_on:
      - mysql
    networks:
      - mynetwork

  caddy:
    image: caddy:2-alpine
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./:/var/www
    ports:
      - 8080:80
    depends_on:
      - php
    networks:
      - mynetwork

volumes:
  mysql_data:
